name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v2.0.0-rc.2

